CREATE TABLE IF NOT EXISTS musics (
    album_id INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    artist VARCHAR(255) ,
    release_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS wa (
title VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS you (
title VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS tyu (
title VARCHAR(255) NOT NULL);

